name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ctraft.3dsx
            ctraft.smdh
